---
title: "TFG_Víctor"
author: "Victor Manuel Moreno Jim?nez"
date: "15 de diciembre de 2015"
output: beamer_presentation
---

## Título
"Prediciendo las elecciones españolas mediante twitter"

## Abstract/ Resumen
Twitter es una red de microblogs donde los usuarios pueden escribir mensajes de corta longitud (140 carácteres). En este trabajo se investigará el papel que tienen las publicaciones de los usuarios, observando dos variables (valencia emocional de las palabras y la presencia del nombre de determinados partidos políticos) a través del análisis de sentimientos, en el resultado electoral del 20/diciembre/2015.

## Introducción

### Twitter como herramienta para expresar opiniones

Twitter es un servicio de "microblogging" que comenzó a dar servicio en 2006 y posee más de 20 millones de visitas mensuales. En twitter, cada usuario puede publicar breves mensajes de una longitud de 140 caracteres también llamados "tweets", que son visibles por los demás usuarios (Tumasjan et al., 2010).

El flujo público de las publicaciones de todos los usuarios de todo el mundo constituye una enorme fuente de información a tiempo real (Tumasjan et al., 2010).

La idea que subyace a estas publicaciones es dar a conocer el estado personal de cada usuario (Tumasjan et al., 2010); sin embargo, eventos de especial relevancia para la vida de las personas como son las elecciones influyen en el contenido de las publicaciones de cada usuario.

Por tanto el análisis de la opinión de un amplio grupo de usuarios de twitter nos puede aportar información sobre la intención de voto.

Sin embargo, este punto resulta controvertido, pues mientras algunos analistas políticos tienen la vista en Twitter como un indicador de las diversas opiniones políticas (Skemp, 2009; citado en Tumasjan et al., 2010); otros autores han afirmado que la mayoría de los mensajes constituyen un "parloteo sin sentido" (pearanalytics, 2009; citado en Tumasjan et al., 2010)

### Análisis de sentimientos en twitter (Big data?)

### Intentos anteriores de predecir los resultados electorales a través de twitter (¿es posible?)

